version: '3.8'

services:
  frontend:
    build:
      context: ./diary.front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./diary.srv
      dockerfile: Dockerfile
    ports:
      - "5000:3000"