version: '3.8'

services:
  frontend:
    build:
      context: ./diary.front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./diary.srv
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    environment:
      DB_CONNECTION: "user:password@pgsql:5432"
    networks:
      - app-network
    depends_on:
      - pgsql

  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DiaryDB
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network: